<div class="row">
    <div class="col-md-8" "mainContent">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create Account</h3>
            </div>
            <div class="panel-body">
                <form action="/create" method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1">First Name</label>
                        <input type="textbox" class="form-control" id="firstName" name="firstName" placeholder="Enter first name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Last Name</label>
                        <input type="textbox" class="form-control" id="lastName" name="lasstName" placeholder="Enter last name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="textbox" class="form-control" id="password" name="password" placeholder="Enter password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>