<div class="jumbotron">
    <h1>The css is all bootstrap</h1>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">A</h3>
            </div>
            <div class="panel-body">
                <p>
                   Holder
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">B</h3>
            </div>
            <div class="panel-body">
                <p>
                    This page can handle creation, and viewing of expenses    
                </p>
            </div>
        </div>
    </div>
</div>
