<div class="row">
    <div class="col-md-8" "mainContent">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">&nbsp;</h3>
            </div>
            <div class="panel-body">
                <div id="pieChart"></div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Toolbar</h3>
            </div>
            <div class="panel-body">
                <p>
                    This page can handle creation, and viewing of expenses 
					<?php echo $this->expenses; ?>   
                </p>
            </div>
        </div>
    </div>
</div>


<!-- START D3 SCRIPTS -->
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/4.7.2/d3.min.js"></script>
<script src="/js/d3pie.min.js"></script>
<script>
var expenses = <?php echo $this->expenses; ?>; 

var pie = new d3pie("pieChart", {
	"header": {
		"title": {
			"text": expenses[0].date,
			"fontSize": 34,
			"font": "courier"
		},
		"location": "pie-center",
		"titleSubtitlePadding": 10
	},
	"size": {
		"canvasWidth": 590,
		"pieInnerRadius": "95%",
		"pieOuterRadius": "70%"
	},
	"data": {
		"sortOrder": "label-desc",
		"content": [
			{
				"label": expenses[0].name,
				"value": parseInt(expenses[0].price),
			},
			{
				"label": expenses[1].name,
				"value": parseInt(expenses[1].price),
			},
		]
	},
	"labels": {
		"outer": {
			"format": "label-percentage1",
			"pieDistance": 20
		},
		"inner": {
			"format": "none"
		},
		"mainLabel": {
			"fontSize": 11
		},
		"percentage": {
			"color": "#999999",
			"fontSize": 11,
			"decimalPlaces": 0
		},
		"value": {
			"color": "#cccc43",
			"fontSize": 11
		},
		"lines": {
			"enabled": true,
			"color": "#777777"
		},
		"truncation": {
			"enabled": true
		}
	},
	"effects": {
		"pullOutSegmentOnClick": {
			"effect": "linear",
			"speed": 400,
			"size": 8
		}
	},
	"misc": {
		"colors": {
			"segmentStroke": "#000000"
		}
	}
});
</script>
<!--END D3 SCRIPTS-->