<div class="jumbotron">
    <h1>The css is all bootstrap</h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">A</h3>
            </div>
            <div class="panel-body">
                <p>
                   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sapien magna, commodo ut tempor a, condimentum vel turpis. Cras vitae posuere nisl. Integer fringilla dui quis tristique dapibus. Fusce lacinia lacus nunc, et ultrices diam euismod nec. Ut augue orci, finibus et felis nec, dictum finibus augue. Curabitur blandit ligula hendrerit ipsum egestas, ut porta massa sodales. Curabitur nulla mauris, tempor et viverra id, interdum ac dolor. Maecenas euismod felis in nisl tincidunt, sed sollicitudin lectus faucibus. Proin nec tincidunt elit. Vivamus erat ipsum, luctus sed convallis in, blandit volutpat quam. Maecenas sit amet aliquet ante. Proin accumsan sagittis molestie. Sed diam elit, luctus et maximus in, feugiat nec tellus. 
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">B</h3>
            </div>
            <div class="panel-body">
                <p>
                    Pellentesque purus enim, luctus non venenatis nec, interdum nec enim. Sed commodo posuere gravida. Aenean suscipit orci porta est efficitur malesuada. In nec faucibus tortor, a ultricies metus. Integer sed tempus leo. Fusce purus metus, cursus sed congue ut, rhoncus sit amet neque. Maecenas pulvinar lobortis purus in congue. Cras blandit gravida dui, et blandit purus volutpat sed. Nunc pharetra ante nec velit efficitur, quis gravida felis iaculis. Pellentesque volutpat sapien in consequat rutrum. Ut tempus ac tortor sed tempor. Sed at velit sed neque blandit pretium. Donec vitae faucibus mauris. Praesent eget metus dui. Cras tincidunt ligula est, semper vestibulum est pulvinar nec.
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"C</h3>
            </div>
            <div class="panel-body">
                <p>
                    Duis urna lorem, lobortis non nibh id, efficitur commodo nibh. Phasellus turpis erat, luctus eu neque quis, sagittis rhoncus orci. Nullam auctor massa libero, luctus laoreet nisl facilisis in. Vestibulum laoreet convallis feugiat. Praesent viverra semper est a elementum. Etiam laoreet lacinia lacus a viverra. Praesent dictum ligula porta leo consectetur, a iaculis eros pulvinar. Maecenas lectus sapien, volutpat quis placerat eu, accumsan at purus. Proin efficitur urna sed magna mattis, et rutrum justo ullamcorper. Sed nibh nisl, congue sed scelerisque eu, laoreet aliquet eros. Suspendisse ac sapien sed lorem eleifend maximus. Phasellus magna neque, blandit sit amet tristique vel, pharetra et nunc. Curabitur efficitur nibh vitae sem facilisis, eu dapibus ex blandit. Nullam a arcu quis quam euismod euismod vitae id lectus.
                </p>
            </div>
        </div>
    </div>
</div>
